### ISSUE TITLE
Payload incorrect (according to the documentation)

### ISSUE THREAD

**Issue by PierreYves** [ker0x/cakephp-push#10]
Hi,

The Payload is incorrect according to the FCM documentation (https://console.firebase.google.com/project/jobzr-afbd0/settings/cloudmessaging)

Your payload is:
[to] ...
[notification] ...
[datas] ...
...

In fact, "datas" field must be "data" ;).

**Comment by ker0x** [comment]
@PierreYves Thank you for reporting this issue, it should be resolved now :) !
