### ISSUE TITLE
Notification with sound

### ISSUE THREAD

**Issue by stvmachine** [ker0x/cakephp-push#22]
Hi, how i configure for the notification goes with sound.

Thx

**Comment by ker0x** [comment]
Hello,

You just have to pass the key **sound** to the notification array

```
$adapter = new Fcm();
$adapter
    ->setTokens(['1', '2', '3', '4'])
    ->setNotification([
        'title' => 'Hello World',
        'body' => 'My awesome Hello World!',
        'sound' => 'default'
    ]);
```

[https://firebase.google.com/docs/cloud-messaging/http-server-ref#table2](https://firebase.google.com/docs/cloud-messaging/http-server-ref#table2)
