### ISSUE TITLE
Can't load the plugins

### ISSUE THREAD

**Issue by cyrusjayson07** [ker0x/cakephp-push#23]
Error: The application is trying to load a file from the ker0x/Push plugin. 

Make sure your plugin ker0x/Push is in the /var/www/projectx/api/plugins/ directory and was loaded.

I followed the instruction.

**Comment by ker0x** [comment]
Hello @cyrusjayson07, thanks for reporting this issue.

Indeed there is an error in the documentation, to enable the plugin you have to type the following command: `bin/cake plugin load Kerox/Push -b` or add the following line to the `bootstrap.php`:

```
Plugin::load('Kerox/Push', ['bootstrap' => true]);
```
